PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZZCA_T_FUNCCONF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZZCA_T_FUNCCONF-ID_IF .
    FIELD ZZCA_T_FUNCCONF-FIELD_NAME .
    FIELD ZZCA_T_FUNCCONF-FIELD_DIRECTION .
    FIELD ZZCA_T_FUNCCONF-FIELD_SOURCE .
    FIELD ZZCA_T_FUNCCONF-FIELD_DATAELEMENT .
    FIELD ZZCA_T_FUNCCONF-ALV_POSITION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZZCA_T_FUNCCONF-ID_IF .
    FIELD ZZCA_T_FUNCCONF-FIELD_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
