PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZZCA_T_HARDC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZZCA_T_HARDC-PROCESSO .
    FIELD ZZCA_T_HARDC-PARAMETRO .
    FIELD ZZCA_T_HARDC-ITEM .
    FIELD ZZCA_T_HARDC-SINAL .
    FIELD ZZCA_T_HARDC-OPCAO .
    FIELD ZZCA_T_HARDC-INFERIOR .
    FIELD ZZCA_T_HARDC-SUPERIOR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZZCA_T_HARDC-PROCESSO .
    FIELD ZZCA_T_HARDC-PARAMETRO .
    FIELD ZZCA_T_HARDC-ITEM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
