* VCL-Modifications
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZZCA_T_OBJCONF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZZCA_T_OBJCONF-ID_IF .
    FIELD ZZCA_T_OBJCONF-OBJECT_TYPE .
    FIELD ZZCA_T_OBJCONF-IN_STRUCT_NAME .
    FIELD ZZCA_T_OBJCONF-OUT_STRUCT_NAME .
    FIELD ZZCA_T_OBJCONF-PO_TYPE .
    FIELD ZZCA_T_OBJCONF-FM_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZZCA_T_OBJCONF-ID_IF .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
*
PROCESS ON VALUE-REQUEST.
    FIELD  ZZCA_T_OBJCONF-ID_IF MODULE VCL_HELP_VALUES.
