PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZZCA_T_IFCONF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZZCA_T_IFCONF-ID_IF .
    FIELD ZZCA_T_IFCONF-TYPE_IF .
    FIELD ZZCA_T_IFCONF-DIRECTION .
    FIELD ZZCA_T_IFCONF-ACTIVE .
    FIELD ZZCA_T_IFCONF-REPROC .
    FIELD ZZCA_T_IFCONF-REPROC_IDOC .
    FIELD ZZCA_T_IFCONF-GROUP_IF .
    FIELD ZZCA_T_IFCONF-EMAIL .
    FIELD ZZCA_T_IFCONF-EMAIL_PROFILE .
    FIELD ZZCA_T_IFCONF-CHECK_IDOC .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   CHAIN.
    FIELD ZZCA_T_IFCONFT-DESCR .
    MODULE SET_TXT_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZZCA_T_IFCONF-ID_IF .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
