PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZZCA_T_IFCF_GEO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZZCA_T_IFCF_GEO-LAND1 .
    FIELD ZZCA_T_IFCF_GEO-TAB_REG_EXEC .
    FIELD ZZCA_T_IFCF_GEO-TAB_IFSEARCH .
    FIELD ZZCA_T_IFCF_GEO-TAB_IFXML .
    FIELD ZZCA_T_IFCF_GEO-TAB_IFOBJECT .
    FIELD ZZCA_T_IFCF_GEO-TAB_IFMESSAGE .
    FIELD ZZCA_T_IFCF_GEO-TAB_IFFUNCVIEW .
    FIELD ZZCA_T_IFCF_GEO-INT_NUM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZZCA_T_IFCF_GEO-LAND1 .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
